name: Build RPM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:38

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install RPM tools
      run: |
        dnf install -y python3.10
        dnf install -y systemd systemd-devel rpm-build rpmdevtools gettext python3-devel python3-setuptools python3-systemd
        dnf install -y 'dnf-command(builddep)'

    - name: Prepare build environment
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp sos.spec ~/rpmbuild/SPECS/
        python3 setup.py sdist
        cp dist/* ~/rpmbuild/SOURCES/

    - name: Build RPM
      run: |
        rpmbuild -ba ~/rpmbuild/SPECS/sos.spec